Sync to dev
qbicsoftware/omero-portlet pull request #59
Opened 2021-12-23 11:27 UTC by luiskuhn

Sync this baby to dev :)

2021-12-23 11:35 UTC, Steffengreiner requested changes
Heya @luiskuhn nice work 👍 
However I'd advice against merging the `master` branch into `development `directly, since the `hotfix` is the only changes that happened it would make more sense to merge the `hotfix `branch into `development.` 
You could also think about bumping the version on the `hotfix `branch with a minor version increase and adding a SNAPSHOT tag (Also adding a seperate section to the changelog) to indicate that the version on `development` is a snapshot.
I made a similiar PR for the [barcode-dragon-portlet](https://github.com/qbicsoftware/barcode-dragon-portlet/pull/35/files)

2022-01-04 10:01 UTC, luiskuhn commented
Makes sense, I'm on it

2022-01-10 12:52 UTC, jenniferboedker commented on docs/conf.py
> +version = '1.3.5'
```suggestion
version = '1.3.6'
```

2022-01-10 12:52 UTC, jenniferboedker commented on docs/conf.py
> +release = '1.3.5'
```suggestion
release = '1.3.6'
```

2022-01-10 12:59 UTC, merged